//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace HACCP.Report.Rpt.SelfAudit {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("SelfAuditDB")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class SelfAuditDB : global::System.Data.DataSet {
        
        private SelfAuditPlanTDataTable tableSelfAuditPlanT;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public SelfAuditDB() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected SelfAuditDB(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["SelfAuditPlanT"] != null)) {
                    base.Tables.Add(new SelfAuditPlanTDataTable(ds.Tables["SelfAuditPlanT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SelfAuditPlanTDataTable SelfAuditPlanT {
            get {
                return this.tableSelfAuditPlanT;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            SelfAuditDB cln = ((SelfAuditDB)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["SelfAuditPlanT"] != null)) {
                    base.Tables.Add(new SelfAuditPlanTDataTable(ds.Tables["SelfAuditPlanT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableSelfAuditPlanT = ((SelfAuditPlanTDataTable)(base.Tables["SelfAuditPlanT"]));
            if ((initTable == true)) {
                if ((this.tableSelfAuditPlanT != null)) {
                    this.tableSelfAuditPlanT.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "SelfAuditDB";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/SelfAuditDB.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableSelfAuditPlanT = new SelfAuditPlanTDataTable();
            base.Tables.Add(this.tableSelfAuditPlanT);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializeSelfAuditPlanT() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            SelfAuditDB ds = new SelfAuditDB();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void SelfAuditPlanTRowChangeEventHandler(object sender, SelfAuditPlanTRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class SelfAuditPlanTDataTable : global::System.Data.TypedTableBase<SelfAuditPlanTRow> {
            
            private global::System.Data.DataColumn columnself_audit_title;
            
            private global::System.Data.DataColumn columnself_audit_date;
            
            private global::System.Data.DataColumn columnself_audit_plan_no;
            
            private global::System.Data.DataColumn columnself_audit_purpose;
            
            private global::System.Data.DataColumn columnself_audit_plan;
            
            private global::System.Data.DataColumn columnself_audit_doc_revision_plan;
            
            private global::System.Data.DataColumn columnself_audit_special;
            
            private global::System.Data.DataColumn columnself_audit_s_emp_cd;
            
            private global::System.Data.DataColumn columnself_audit_s_emp_time;
            
            private global::System.Data.DataColumn columnself_audit_pc_emp_cd;
            
            private global::System.Data.DataColumn columnself_audit_pc_emp_time;
            
            private global::System.Data.DataColumn columnself_audit_p_emp_cd;
            
            private global::System.Data.DataColumn columnself_audit_p_emp_time;
            
            private global::System.Data.DataColumn columnself_audit_pc_comments;
            
            private global::System.Data.DataColumn columnself_audit_s_emp_nm;
            
            private global::System.Data.DataColumn columnself_audit_pc_emp_nm;
            
            private global::System.Data.DataColumn columnself_audit_p_emp_nm;
            
            private global::System.Data.DataColumn columnself_audit_auditor_nm;
            
            private global::System.Data.DataColumn columnself_audit_doc_file_nm;
            
            private global::System.Data.DataColumn columnself_audit_file_upload_step;
            
            private global::System.Data.DataColumn columnself_audit_file_upload_emp_nm;
            
            private global::System.Data.DataColumn columnself_audit_s_emp_sign;
            
            private global::System.Data.DataColumn columnself_audit_pc_emp_sign;
            
            private global::System.Data.DataColumn columnself_audit_p_emp_sign;
            
            private global::System.Data.DataColumn columncompany_image;
            
            private global::System.Data.DataColumn columnupload_file_step_nm;
            
            private global::System.Data.DataColumn columnself_audit_p_comments;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public SelfAuditPlanTDataTable() {
                this.TableName = "SelfAuditPlanT";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal SelfAuditPlanTDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected SelfAuditPlanTDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_titleColumn {
                get {
                    return this.columnself_audit_title;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_dateColumn {
                get {
                    return this.columnself_audit_date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_plan_noColumn {
                get {
                    return this.columnself_audit_plan_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_purposeColumn {
                get {
                    return this.columnself_audit_purpose;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_planColumn {
                get {
                    return this.columnself_audit_plan;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_doc_revision_planColumn {
                get {
                    return this.columnself_audit_doc_revision_plan;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_specialColumn {
                get {
                    return this.columnself_audit_special;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_s_emp_cdColumn {
                get {
                    return this.columnself_audit_s_emp_cd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_s_emp_timeColumn {
                get {
                    return this.columnself_audit_s_emp_time;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_pc_emp_cdColumn {
                get {
                    return this.columnself_audit_pc_emp_cd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_pc_emp_timeColumn {
                get {
                    return this.columnself_audit_pc_emp_time;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_p_emp_cdColumn {
                get {
                    return this.columnself_audit_p_emp_cd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_p_emp_timeColumn {
                get {
                    return this.columnself_audit_p_emp_time;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_pc_commentsColumn {
                get {
                    return this.columnself_audit_pc_comments;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_s_emp_nmColumn {
                get {
                    return this.columnself_audit_s_emp_nm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_pc_emp_nmColumn {
                get {
                    return this.columnself_audit_pc_emp_nm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_p_emp_nmColumn {
                get {
                    return this.columnself_audit_p_emp_nm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_auditor_nmColumn {
                get {
                    return this.columnself_audit_auditor_nm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_doc_file_nmColumn {
                get {
                    return this.columnself_audit_doc_file_nm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_file_upload_stepColumn {
                get {
                    return this.columnself_audit_file_upload_step;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_file_upload_emp_nmColumn {
                get {
                    return this.columnself_audit_file_upload_emp_nm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_s_emp_signColumn {
                get {
                    return this.columnself_audit_s_emp_sign;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_pc_emp_signColumn {
                get {
                    return this.columnself_audit_pc_emp_sign;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_p_emp_signColumn {
                get {
                    return this.columnself_audit_p_emp_sign;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn company_imageColumn {
                get {
                    return this.columncompany_image;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn upload_file_step_nmColumn {
                get {
                    return this.columnupload_file_step_nm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn self_audit_p_commentsColumn {
                get {
                    return this.columnself_audit_p_comments;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public SelfAuditPlanTRow this[int index] {
                get {
                    return ((SelfAuditPlanTRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event SelfAuditPlanTRowChangeEventHandler SelfAuditPlanTRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event SelfAuditPlanTRowChangeEventHandler SelfAuditPlanTRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event SelfAuditPlanTRowChangeEventHandler SelfAuditPlanTRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event SelfAuditPlanTRowChangeEventHandler SelfAuditPlanTRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddSelfAuditPlanTRow(SelfAuditPlanTRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public SelfAuditPlanTRow AddSelfAuditPlanTRow(
                        string self_audit_title, 
                        string self_audit_date, 
                        string self_audit_plan_no, 
                        string self_audit_purpose, 
                        string self_audit_plan, 
                        string self_audit_doc_revision_plan, 
                        string self_audit_special, 
                        string self_audit_s_emp_cd, 
                        string self_audit_s_emp_time, 
                        string self_audit_pc_emp_cd, 
                        string self_audit_pc_emp_time, 
                        string self_audit_p_emp_cd, 
                        string self_audit_p_emp_time, 
                        string self_audit_pc_comments, 
                        string self_audit_s_emp_nm, 
                        string self_audit_pc_emp_nm, 
                        string self_audit_p_emp_nm, 
                        string self_audit_auditor_nm, 
                        string self_audit_doc_file_nm, 
                        string self_audit_file_upload_step, 
                        string self_audit_file_upload_emp_nm, 
                        byte[] self_audit_s_emp_sign, 
                        byte[] self_audit_pc_emp_sign, 
                        byte[] self_audit_p_emp_sign, 
                        byte[] company_image, 
                        string upload_file_step_nm, 
                        string self_audit_p_comments) {
                SelfAuditPlanTRow rowSelfAuditPlanTRow = ((SelfAuditPlanTRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        self_audit_title,
                        self_audit_date,
                        self_audit_plan_no,
                        self_audit_purpose,
                        self_audit_plan,
                        self_audit_doc_revision_plan,
                        self_audit_special,
                        self_audit_s_emp_cd,
                        self_audit_s_emp_time,
                        self_audit_pc_emp_cd,
                        self_audit_pc_emp_time,
                        self_audit_p_emp_cd,
                        self_audit_p_emp_time,
                        self_audit_pc_comments,
                        self_audit_s_emp_nm,
                        self_audit_pc_emp_nm,
                        self_audit_p_emp_nm,
                        self_audit_auditor_nm,
                        self_audit_doc_file_nm,
                        self_audit_file_upload_step,
                        self_audit_file_upload_emp_nm,
                        self_audit_s_emp_sign,
                        self_audit_pc_emp_sign,
                        self_audit_p_emp_sign,
                        company_image,
                        upload_file_step_nm,
                        self_audit_p_comments};
                rowSelfAuditPlanTRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowSelfAuditPlanTRow);
                return rowSelfAuditPlanTRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                SelfAuditPlanTDataTable cln = ((SelfAuditPlanTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new SelfAuditPlanTDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columnself_audit_title = base.Columns["self_audit_title"];
                this.columnself_audit_date = base.Columns["self_audit_date"];
                this.columnself_audit_plan_no = base.Columns["self_audit_plan_no"];
                this.columnself_audit_purpose = base.Columns["self_audit_purpose"];
                this.columnself_audit_plan = base.Columns["self_audit_plan"];
                this.columnself_audit_doc_revision_plan = base.Columns["self_audit_doc_revision_plan"];
                this.columnself_audit_special = base.Columns["self_audit_special"];
                this.columnself_audit_s_emp_cd = base.Columns["self_audit_s_emp_cd"];
                this.columnself_audit_s_emp_time = base.Columns["self_audit_s_emp_time"];
                this.columnself_audit_pc_emp_cd = base.Columns["self_audit_pc_emp_cd"];
                this.columnself_audit_pc_emp_time = base.Columns["self_audit_pc_emp_time"];
                this.columnself_audit_p_emp_cd = base.Columns["self_audit_p_emp_cd"];
                this.columnself_audit_p_emp_time = base.Columns["self_audit_p_emp_time"];
                this.columnself_audit_pc_comments = base.Columns["self_audit_pc_comments"];
                this.columnself_audit_s_emp_nm = base.Columns["self_audit_s_emp_nm"];
                this.columnself_audit_pc_emp_nm = base.Columns["self_audit_pc_emp_nm"];
                this.columnself_audit_p_emp_nm = base.Columns["self_audit_p_emp_nm"];
                this.columnself_audit_auditor_nm = base.Columns["self_audit_auditor_nm"];
                this.columnself_audit_doc_file_nm = base.Columns["self_audit_doc_file_nm"];
                this.columnself_audit_file_upload_step = base.Columns["self_audit_file_upload_step"];
                this.columnself_audit_file_upload_emp_nm = base.Columns["self_audit_file_upload_emp_nm"];
                this.columnself_audit_s_emp_sign = base.Columns["self_audit_s_emp_sign"];
                this.columnself_audit_pc_emp_sign = base.Columns["self_audit_pc_emp_sign"];
                this.columnself_audit_p_emp_sign = base.Columns["self_audit_p_emp_sign"];
                this.columncompany_image = base.Columns["company_image"];
                this.columnupload_file_step_nm = base.Columns["upload_file_step_nm"];
                this.columnself_audit_p_comments = base.Columns["self_audit_p_comments"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columnself_audit_title = new global::System.Data.DataColumn("self_audit_title", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_title);
                this.columnself_audit_date = new global::System.Data.DataColumn("self_audit_date", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_date);
                this.columnself_audit_plan_no = new global::System.Data.DataColumn("self_audit_plan_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_plan_no);
                this.columnself_audit_purpose = new global::System.Data.DataColumn("self_audit_purpose", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_purpose);
                this.columnself_audit_plan = new global::System.Data.DataColumn("self_audit_plan", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_plan);
                this.columnself_audit_doc_revision_plan = new global::System.Data.DataColumn("self_audit_doc_revision_plan", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_doc_revision_plan);
                this.columnself_audit_special = new global::System.Data.DataColumn("self_audit_special", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_special);
                this.columnself_audit_s_emp_cd = new global::System.Data.DataColumn("self_audit_s_emp_cd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_s_emp_cd);
                this.columnself_audit_s_emp_time = new global::System.Data.DataColumn("self_audit_s_emp_time", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_s_emp_time);
                this.columnself_audit_pc_emp_cd = new global::System.Data.DataColumn("self_audit_pc_emp_cd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_pc_emp_cd);
                this.columnself_audit_pc_emp_time = new global::System.Data.DataColumn("self_audit_pc_emp_time", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_pc_emp_time);
                this.columnself_audit_p_emp_cd = new global::System.Data.DataColumn("self_audit_p_emp_cd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_p_emp_cd);
                this.columnself_audit_p_emp_time = new global::System.Data.DataColumn("self_audit_p_emp_time", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_p_emp_time);
                this.columnself_audit_pc_comments = new global::System.Data.DataColumn("self_audit_pc_comments", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_pc_comments);
                this.columnself_audit_s_emp_nm = new global::System.Data.DataColumn("self_audit_s_emp_nm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_s_emp_nm);
                this.columnself_audit_pc_emp_nm = new global::System.Data.DataColumn("self_audit_pc_emp_nm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_pc_emp_nm);
                this.columnself_audit_p_emp_nm = new global::System.Data.DataColumn("self_audit_p_emp_nm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_p_emp_nm);
                this.columnself_audit_auditor_nm = new global::System.Data.DataColumn("self_audit_auditor_nm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_auditor_nm);
                this.columnself_audit_doc_file_nm = new global::System.Data.DataColumn("self_audit_doc_file_nm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_doc_file_nm);
                this.columnself_audit_file_upload_step = new global::System.Data.DataColumn("self_audit_file_upload_step", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_file_upload_step);
                this.columnself_audit_file_upload_emp_nm = new global::System.Data.DataColumn("self_audit_file_upload_emp_nm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_file_upload_emp_nm);
                this.columnself_audit_s_emp_sign = new global::System.Data.DataColumn("self_audit_s_emp_sign", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_s_emp_sign);
                this.columnself_audit_pc_emp_sign = new global::System.Data.DataColumn("self_audit_pc_emp_sign", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_pc_emp_sign);
                this.columnself_audit_p_emp_sign = new global::System.Data.DataColumn("self_audit_p_emp_sign", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_p_emp_sign);
                this.columncompany_image = new global::System.Data.DataColumn("company_image", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncompany_image);
                this.columnupload_file_step_nm = new global::System.Data.DataColumn("upload_file_step_nm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnupload_file_step_nm);
                this.columnself_audit_p_comments = new global::System.Data.DataColumn("self_audit_p_comments", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnself_audit_p_comments);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public SelfAuditPlanTRow NewSelfAuditPlanTRow() {
                return ((SelfAuditPlanTRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new SelfAuditPlanTRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(SelfAuditPlanTRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SelfAuditPlanTRowChanged != null)) {
                    this.SelfAuditPlanTRowChanged(this, new SelfAuditPlanTRowChangeEvent(((SelfAuditPlanTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SelfAuditPlanTRowChanging != null)) {
                    this.SelfAuditPlanTRowChanging(this, new SelfAuditPlanTRowChangeEvent(((SelfAuditPlanTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SelfAuditPlanTRowDeleted != null)) {
                    this.SelfAuditPlanTRowDeleted(this, new SelfAuditPlanTRowChangeEvent(((SelfAuditPlanTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SelfAuditPlanTRowDeleting != null)) {
                    this.SelfAuditPlanTRowDeleting(this, new SelfAuditPlanTRowChangeEvent(((SelfAuditPlanTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemoveSelfAuditPlanTRow(SelfAuditPlanTRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                SelfAuditDB ds = new SelfAuditDB();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SelfAuditPlanTDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class SelfAuditPlanTRow : global::System.Data.DataRow {
            
            private SelfAuditPlanTDataTable tableSelfAuditPlanT;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal SelfAuditPlanTRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableSelfAuditPlanT = ((SelfAuditPlanTDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_title {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_titleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_title\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_titleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_date {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_date\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_plan_no {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_plan_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_plan_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_plan_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_purpose {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_purposeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_purpose\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_purposeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_plan {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_planColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_plan\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_planColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_doc_revision_plan {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_doc_revision_planColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_doc_revision_plan\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_doc_revision_planColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_special {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_specialColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_special\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_specialColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_s_emp_cd {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_s_emp_cdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_s_emp_cd\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_s_emp_cdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_s_emp_time {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_s_emp_timeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_s_emp_time\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_s_emp_timeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_pc_emp_cd {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_pc_emp_cdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_pc_emp_cd\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_pc_emp_cdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_pc_emp_time {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_pc_emp_timeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_pc_emp_time\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_pc_emp_timeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_p_emp_cd {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_p_emp_cdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_p_emp_cd\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_p_emp_cdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_p_emp_time {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_p_emp_timeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_p_emp_time\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_p_emp_timeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_pc_comments {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_pc_commentsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_pc_comments\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_pc_commentsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_s_emp_nm {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_s_emp_nmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_s_emp_nm\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_s_emp_nmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_pc_emp_nm {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_pc_emp_nmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_pc_emp_nm\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_pc_emp_nmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_p_emp_nm {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_p_emp_nmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_p_emp_nm\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_p_emp_nmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_auditor_nm {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_auditor_nmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_auditor_nm\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_auditor_nmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_doc_file_nm {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_doc_file_nmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_doc_file_nm\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_doc_file_nmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_file_upload_step {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_file_upload_stepColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_file_upload_step\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_file_upload_stepColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_file_upload_emp_nm {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_file_upload_emp_nmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_file_upload_emp_nm\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_file_upload_emp_nmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public byte[] self_audit_s_emp_sign {
                get {
                    try {
                        return ((byte[])(this[this.tableSelfAuditPlanT.self_audit_s_emp_signColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_s_emp_sign\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_s_emp_signColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public byte[] self_audit_pc_emp_sign {
                get {
                    try {
                        return ((byte[])(this[this.tableSelfAuditPlanT.self_audit_pc_emp_signColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_pc_emp_sign\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_pc_emp_signColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public byte[] self_audit_p_emp_sign {
                get {
                    try {
                        return ((byte[])(this[this.tableSelfAuditPlanT.self_audit_p_emp_signColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_p_emp_sign\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_p_emp_signColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public byte[] company_image {
                get {
                    try {
                        return ((byte[])(this[this.tableSelfAuditPlanT.company_imageColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'company_image\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.company_imageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string upload_file_step_nm {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.upload_file_step_nmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'upload_file_step_nm\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.upload_file_step_nmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string self_audit_p_comments {
                get {
                    try {
                        return ((string)(this[this.tableSelfAuditPlanT.self_audit_p_commentsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'SelfAuditPlanT\' 테이블의 \'self_audit_p_comments\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableSelfAuditPlanT.self_audit_p_commentsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_titleNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_titleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_titleNull() {
                this[this.tableSelfAuditPlanT.self_audit_titleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_dateNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_dateNull() {
                this[this.tableSelfAuditPlanT.self_audit_dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_plan_noNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_plan_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_plan_noNull() {
                this[this.tableSelfAuditPlanT.self_audit_plan_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_purposeNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_purposeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_purposeNull() {
                this[this.tableSelfAuditPlanT.self_audit_purposeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_planNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_planColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_planNull() {
                this[this.tableSelfAuditPlanT.self_audit_planColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_doc_revision_planNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_doc_revision_planColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_doc_revision_planNull() {
                this[this.tableSelfAuditPlanT.self_audit_doc_revision_planColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_specialNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_specialColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_specialNull() {
                this[this.tableSelfAuditPlanT.self_audit_specialColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_s_emp_cdNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_s_emp_cdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_s_emp_cdNull() {
                this[this.tableSelfAuditPlanT.self_audit_s_emp_cdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_s_emp_timeNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_s_emp_timeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_s_emp_timeNull() {
                this[this.tableSelfAuditPlanT.self_audit_s_emp_timeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_pc_emp_cdNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_pc_emp_cdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_pc_emp_cdNull() {
                this[this.tableSelfAuditPlanT.self_audit_pc_emp_cdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_pc_emp_timeNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_pc_emp_timeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_pc_emp_timeNull() {
                this[this.tableSelfAuditPlanT.self_audit_pc_emp_timeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_p_emp_cdNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_p_emp_cdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_p_emp_cdNull() {
                this[this.tableSelfAuditPlanT.self_audit_p_emp_cdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_p_emp_timeNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_p_emp_timeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_p_emp_timeNull() {
                this[this.tableSelfAuditPlanT.self_audit_p_emp_timeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_pc_commentsNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_pc_commentsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_pc_commentsNull() {
                this[this.tableSelfAuditPlanT.self_audit_pc_commentsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_s_emp_nmNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_s_emp_nmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_s_emp_nmNull() {
                this[this.tableSelfAuditPlanT.self_audit_s_emp_nmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_pc_emp_nmNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_pc_emp_nmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_pc_emp_nmNull() {
                this[this.tableSelfAuditPlanT.self_audit_pc_emp_nmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_p_emp_nmNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_p_emp_nmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_p_emp_nmNull() {
                this[this.tableSelfAuditPlanT.self_audit_p_emp_nmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_auditor_nmNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_auditor_nmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_auditor_nmNull() {
                this[this.tableSelfAuditPlanT.self_audit_auditor_nmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_doc_file_nmNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_doc_file_nmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_doc_file_nmNull() {
                this[this.tableSelfAuditPlanT.self_audit_doc_file_nmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_file_upload_stepNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_file_upload_stepColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_file_upload_stepNull() {
                this[this.tableSelfAuditPlanT.self_audit_file_upload_stepColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_file_upload_emp_nmNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_file_upload_emp_nmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_file_upload_emp_nmNull() {
                this[this.tableSelfAuditPlanT.self_audit_file_upload_emp_nmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_s_emp_signNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_s_emp_signColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_s_emp_signNull() {
                this[this.tableSelfAuditPlanT.self_audit_s_emp_signColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_pc_emp_signNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_pc_emp_signColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_pc_emp_signNull() {
                this[this.tableSelfAuditPlanT.self_audit_pc_emp_signColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_p_emp_signNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_p_emp_signColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_p_emp_signNull() {
                this[this.tableSelfAuditPlanT.self_audit_p_emp_signColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Iscompany_imageNull() {
                return this.IsNull(this.tableSelfAuditPlanT.company_imageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setcompany_imageNull() {
                this[this.tableSelfAuditPlanT.company_imageColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isupload_file_step_nmNull() {
                return this.IsNull(this.tableSelfAuditPlanT.upload_file_step_nmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setupload_file_step_nmNull() {
                this[this.tableSelfAuditPlanT.upload_file_step_nmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isself_audit_p_commentsNull() {
                return this.IsNull(this.tableSelfAuditPlanT.self_audit_p_commentsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setself_audit_p_commentsNull() {
                this[this.tableSelfAuditPlanT.self_audit_p_commentsColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class SelfAuditPlanTRowChangeEvent : global::System.EventArgs {
            
            private SelfAuditPlanTRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public SelfAuditPlanTRowChangeEvent(SelfAuditPlanTRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public SelfAuditPlanTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591